### ISSUE TITLE
AdmPwd source code version

### ISSUE THREAD

**Issue by bertrandspt** [jformacek/admpwd#3]
Hi Jiri,

First, thanks a lot for sharing your code.

I forked admpwd CSE last year to make it work through a VPN client called 'Ercom Cryptosmart PC'.
I had to rewrite some parts of your original code to avoid RPC requests (not allowed in my society's VPN channel), and built it as a console application to launch it on demand via a windows service (for some reasons, remote laptops can't perform gpupdates through the VPN channel).
I called it "LAPS mobile", and it works great.

"LAPS mobile" was originaly based on LAPS 5.2.0.0, so i wanted to update it with the lastest version of your code.
My society's desktop computers are equiped whith version 6.0.1.0, and the lastest version i found on Microsoft website is 6.2.x, released in september 2016.

But, according to the assembly infos of the VS project, the version you share on github is 5.2.1.0.
However, it seems that you updated the project on 4th of july 2017, so later than the 6.2.x release.

So can you tell me/us if there is an error/oversight on the assembly infos, or i you decided to stop sharing the source code since the 5.2.1.0 version ?

Thanks a lot.

Bertrand

**Comment by jformacek** [comment]
Hello,
source code published there is pre- MS LAPS source - basically the version that was then rebranded by MS as LAPS. I don't have permission to publish MS source code, and that's why the version here is lower - I keep it lower intentionally so it would not replace installed LAPS version if someone would run installer by mistake - in fact, this source and MS LAPS share the same product ID, so for MSInstaller, it's the same product.

However, I plan to publish small updates here if time permits, and in the future may decide to increase the version number over MS LAPS as it seems that MS APS does not have any roadmap anyway and newer versions are not very likely to come. So in the future, i _may_ extend this AdmPwd solution as lightweight, opensource version of MS LAPS, with features that may be missing in MS LAPS, and as free companion to AdmPwd.E.

Does this answer the question?

Regards,
Jiri

**Comment by bertrandspt** [comment]
OK, thanks for the answer.
Regards,
Bertrand
